package airgap

import (

        "fmt"
	//"os"
	//"github.com/ghodss/yaml"
	"github.com/openshift/installer/pkg/asset"
	//"github.com/openshift/installer/pkg/types"
        "github.com/spf13/viper"
)

type AirgapPackage struct {
        File   *asset.File          `json:"file"`
	url    string
	ocp_ver string
	rhcos_ver string
	platform string
	dest string
	pull_secret string
}

var _ asset.WritableAsset = (*AirgapPackage)(nil)


// Files returns the files generated by the asset.
func (a *AirgapPackage) Files() []*asset.File {
        if a.File != nil {
                return []*asset.File{a.File}
        }
        return []*asset.File{}
}

// Load returns the installconfig from disk.
func (a *AirgapPackage) Load(f asset.FileFetcher) (found bool, err error) {

	fmt.Println("Creating airgap package")

	a.ocp_ver = viper.GetString("ocp_ver")
	a.rhcos_ver = viper.GetString("rhcos_ver")
	//a.platform = viper.GetString("platform")
	a.dest = viper.GetString("dest")
	a.pull_secret = viper.GetString("pull_secret")

	rhcosMeta := &rhcosReleaseMetaData{}
	//mirrorRelease := &mirrorReleaseMetaData{}

	rhcosMeta.createAirgapPackage(a)
	//rhcosMeta.createAirgapPackage(rhcos_ver, dest , platform)
	//mirrorRelease.pullMirrorImages(ocp_ver, dest, pull_secret)

	//mirrorRelease.extractInstaller(config)
	//isoImage.createISOImage(config.Ocpdistribution.Destdir, config.Ocpdistribution.Isofile)

	return true, nil
}

func (a *AirgapPackage) Generate(parents asset.Parents) error {
        rhcosRelease := &rhcosReleaseMetaData{}

        fmt.Println("Airgap Generate is being called")
	parents.Get(
		rhcosRelease,
	)
	//rhcosMetaData = &rhcosReleaseMetaData{}

	rhcosRelease.Generate(parents)

        return nil
}

// Dependencies returns no dependencies.
func (a *AirgapPackage) Dependencies() []asset.Asset {
	return []asset.Asset{
		&rhcosReleaseMetaData{},
                &mirrorReleaseMetaData{},
	}
        fmt.Println("In the deps")
	return nil
}

// Name returns the human-friendly name of the asset.
func (a *AirgapPackage) Name() string {
	return "Airgap Package"
}
